// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoSancesWebAPI.Data;

namespace ProjetoSancesWebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjetoSancesWebAPI.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Telefone")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cliente");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cpf = "08545685238",
                            Nome = "Marta",
                            Telefone = 33225555
                        },
                        new
                        {
                            Id = 2,
                            Cpf = "14785236998",
                            Nome = "Paula",
                            Telefone = 3354288
                        },
                        new
                        {
                            Id = 3,
                            Cpf = "98745632114",
                            Nome = "Laura",
                            Telefone = 55668899
                        },
                        new
                        {
                            Id = 4,
                            Cpf = "95184763252",
                            Nome = "Luiza",
                            Telefone = 6565659
                        },
                        new
                        {
                            Id = 5,
                            Cpf = "96587412365",
                            Nome = "Lucas",
                            Telefone = 565685415
                        },
                        new
                        {
                            Id = 6,
                            Cpf = "85274196385",
                            Nome = "Pedro",
                            Telefone = 456454545
                        },
                        new
                        {
                            Id = 7,
                            Cpf = "32569874196",
                            Nome = "Paulo",
                            Telefone = 987451852
                        });
                });

            modelBuilder.Entity("ProjetoSancesWebAPI.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Situacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ValorTotal")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Pedido");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClienteId = 5,
                            Data = new DateTime(2020, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Situacao = "Analise",
                            ValorTotal = 0.0
                        },
                        new
                        {
                            Id = 2,
                            ClienteId = 1,
                            Data = new DateTime(2020, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Situacao = "Analise",
                            ValorTotal = 0.0
                        },
                        new
                        {
                            Id = 3,
                            ClienteId = 7,
                            Data = new DateTime(2020, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Situacao = "Analise",
                            ValorTotal = 0.0
                        });
                });

            modelBuilder.Entity("ProjetoSancesWebAPI.Models.PedidoProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Desconto")
                        .HasColumnType("float");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("PedidoProduto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Desconto = 0.0,
                            PedidoId = 1,
                            ProdutoId = 1,
                            Quantidade = 1
                        },
                        new
                        {
                            Id = 2,
                            Desconto = 0.0,
                            PedidoId = 1,
                            ProdutoId = 4,
                            Quantidade = 5
                        },
                        new
                        {
                            Id = 3,
                            Desconto = 0.0,
                            PedidoId = 2,
                            ProdutoId = 3,
                            Quantidade = 1
                        },
                        new
                        {
                            Id = 4,
                            Desconto = 0.0,
                            PedidoId = 2,
                            ProdutoId = 6,
                            Quantidade = 2
                        },
                        new
                        {
                            Id = 5,
                            Desconto = 0.0,
                            PedidoId = 2,
                            ProdutoId = 7,
                            Quantidade = 2
                        },
                        new
                        {
                            Id = 6,
                            Desconto = 0.0,
                            PedidoId = 3,
                            ProdutoId = 5,
                            Quantidade = 1
                        },
                        new
                        {
                            Id = 7,
                            Desconto = 0.0,
                            PedidoId = 3,
                            ProdutoId = 2,
                            Quantidade = 1
                        });
                });

            modelBuilder.Entity("ProjetoSancesWebAPI.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ValorUni")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Produto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Filtro Óleo",
                            ValorUni = 12.25
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Embreagem",
                            ValorUni = 145.59999999999999
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Pastilha Freio",
                            ValorUni = 74.989999999999995
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Óleo Motor",
                            ValorUni = 16.800000000000001
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Filtro Ar",
                            ValorUni = 33.0
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "Amortecedor",
                            ValorUni = 120.65000000000001
                        },
                        new
                        {
                            Id = 7,
                            Descricao = "Mão de Obra",
                            ValorUni = 80.0
                        });
                });

            modelBuilder.Entity("ProjetoSancesWebAPI.Models.Pedido", b =>
                {
                    b.HasOne("ProjetoSancesWebAPI.Models.Cliente", "Cliente")
                        .WithMany("Pedido")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjetoSancesWebAPI.Models.PedidoProduto", b =>
                {
                    b.HasOne("ProjetoSancesWebAPI.Models.Pedido", "Pedido")
                        .WithMany("PedidoProduto")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoSancesWebAPI.Models.Produto", "Produto")
                        .WithMany("PedidoProduto")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
